### ISSUE TITLE
--until flag doesn't work

### ISSUE THREAD

**Issue by Rowno** [segmentio/cwlogs#17] opened 2017-07-09 00:19 UTC
The `--until` flag doesn't seem to be working. I've tried both `--until 20m` and `--until 2017-07-05T09:00:00` but it always fetches until now.

**Comment by dfuentes** [comment] 2017-07-17 17:30
Did you try pulling the latest?  I believe this was fixed in https://github.com/segmentio/cwlogs/pull/16, but let me know if it's still an issue.

**Comment by Rowno** [comment] 2017-07-17 18:11
I ran `go get github.com/segmentio/cwlogs` and `--until` still isn't working.

**Comment by dfuentes** [comment] 2017-07-17 18:18
Are you sure that the command you are using is using the latest binary (you may need the `-u` flag to go get, or you can grab the latest mac release from the [releases page](https://github.com/segmentio/cwlogs/releases)?

If that still doesn't work, it would be useful to have a full command you are running that I can reproduce (because `--until` seems to be working for me with the latest version).

**Comment by Rowno** [comment] 2017-07-17 20:44
Running `go get -u github.com/segmentio/cwlogs` fixed it. You should really add a `--version` flag and update the README. 😉

**Closed as completed** 2017-07-17 20:44 UTC
